export const ROUTE_PATHS = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  portal: '/portal',
  dashboard: '/dashboard',
  candidateDashboard: '/candidate/dashboard',
  cvBuilder: '/candidate/cv-builder',
  jobs: '/jobs',
  profile: '/profile',
  recruiter: '/recruiter',
  recruiterMandate: '/recruiter/mandate/:cardId',
  recruiterCandidate: '/recruiter/mandate/:cardId/candidate/:candidateId',
  crm: '/crm',
  manco: '/manco',
  exco: '/exco',
} as const
