export const ROUTE_PATHS = {
  landing: '/',
  login: '/login',
  signup: '/signup',
  portal: '/portal',
  dashboard: '/dashboard',
  candidateDashboard: '/candidate/dashboard',
  cvBuilder: '/candidate/cv-builder',
  jobs: '/jobs',
  profile: '/profile',
  recruiter: '/recruiter',
  recruiterMandates: '/recruiter/mandates',
  recruiterMandate: '/recruiter/mandate/:cardId',
  recruiterCandidate: '/recruiter/mandate/:cardId/candidate/:candidateId',
  recruiterNewMandate: '/recruiter/new-mandate',
  crm: '/crm',
  recruiterCrm: '/recruiter/crm',
  manco: '/manco',
  exco: '/exco',
} as const
