export const ROUTE_PATHS = {
  landing: '/',
  login: '/login',
  resetPassword: '/reset-password',
  signup: '/signup',
  dashboard: '/dashboard',
  candidateDashboard: '/candidate/dashboard',
  cvBuilder: '/candidate/cv-builder',
  jobs: '/jobs',
  profile: '/profile',
  profileCreation: '/profile/create',
  recruiter: '/recruiter',
  recruiterMandate: '/recruiter/mandate/:cardId',
  recruiterCandidate: '/recruiter/mandate/:cardId/candidate/:candidateId',
  recruiterNewMandate: '/recruiter/new-mandate',
  crm: '/crm',
  manco: '/manco',
  exco: '/exco',
} as const
